version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5000:5432"
    expose:
      - "5000"
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=workflow


  app:
    image: 'bags_spring:latest'
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5000/workflow?useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - "SPRING_DATASOURCE_PASSWORD=postgres"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=update"
