server:
  error.include-message: always

logging:
  level:
    org.springframework: ERROR
    com.example.bags: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: app.log
    path: .

spring:

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/workflow
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
